name: CI

on:
  push:
    branches: [ main ]
 
jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Print hello
        run: docker build -t python_volume_app .
            echo Hello, world from build!

  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Print hello
        run: echo Hello, world from deploy
